import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "var(--color-secondary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-background": "var(--color-on-background)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-variant": "var(--color-surface-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-primary": "var(--color-on-primary)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "tertiary-container": "var(--color-tertiary-container)",
        "primary-container": "var(--color-primary-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "deep-navy": "var(--color-deep-navy)",
        "surface-gray": "var(--color-surface-gray)",
        "on-primary-container": "var(--color-on-primary-container)",
        tertiary: "var(--color-tertiary)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        background: "var(--color-background)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "outline-variant": "var(--color-outline-variant)",
        secondary: "var(--color-secondary)",
        "error-container": "var(--color-error-container)",
        error: "var(--color-error)",
        "on-surface": "var(--color-on-surface)",
        surface: "var(--color-surface)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "surface-container": "var(--color-surface-container)",
        outline: "var(--color-outline)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-error": "var(--color-on-error)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        primary: "var(--color-primary)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "inverse-surface": "var(--color-inverse-surface)",
        "soft-blue-bg": "var(--color-soft-blue-bg)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "stack-sm": "4px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "container-max": "85vw",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "85vw",
      },
      fontFamily: {
        sans: ["var(--font-hanken)", "var(--font-cairo)", "sans-serif"],
        arabic: ["var(--font-cairo)", "var(--font-hanken)", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl-mobile": ["32px", { lineHeight: "38px", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "16px", fontWeight: "700" }],
        "price-display": ["28px", { lineHeight: "32px", fontWeight: "800" }],
      },
      boxShadow: {
        elevated: "0px 4px 20px rgba(0, 0, 0, 0.08)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.2s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
